### ISSUE TITLE
Difficulty with evaluation on downstream task of Object detection

### ISSUE THREAD

**Issue by NikhilKanamarla** [kdexd/virtex#11]
Hi, 

I used the setup tutorial to setup Virtex on my local Macbook Pro machine. 

I tried to run Object detection on Pascal VOC and I got this error 
<img width="819" alt="Screen Shot 2020-08-08 at 7 08 44 PM" src="https://user-images.githubusercontent.com/12837489/89721506-56acf800-d9ac-11ea-8f11-d712efdadd9f.png">

Do you have any advice? Did I mess something up during setup?

**Comment by kdexd** [comment]
You need to install https://github.com/nvidia/apex (instructions in README). Word of caution: detection eval requires 13 GB+ GPU memory.

**Comment by NikhilKanamarla** [comment]
Thank you very much, sorry for bothering you.
