### ISSUE TITLE
Reproduction of SPICE results (eval_captioning.py)

### ISSUE THREAD

**Issue by Eladhi** [kdexd/virtex#14]
Hi, nice work - thanks for sharing the code.

I'm trying to reproduce CIDEr & SPICE results, as appear in figure 4 in your paper.
I simply load the pre-trained models (specifically, those that correspond to H=1024 & H=2048 in width-ablation) and run eval_captioning.py, after building the vocabulary.
The values I get are much lower than those in fig. 4, which seems like some inconsistency in the pre/post-processing.
Should I expect the same values in this experiment? If so, is there any change I should perform?

**Comment by kdexd** [comment]
Hi @Eladhi! Thanks for trying out the code. I can confirm this issue, must have slipped in some recent parameter renaming. I will look into it this weekend and let you know.

**Comment by kdexd** [comment]
Fixed in 3b6d628 — I can reproduce the results now. Feel free to re-open this if you face any problems @Eladhi!

**Comment by shayanjoya** [comment]
Hi,
I've trained the model and am able to run inference on a dir of images. However, when I use the --cal-metrics option like below:

python3 scripts/eval_captioning.py --config configs/_base_bicaptioning_R_50_L1_H1024.yaml --checkpoint-path /virtex/tmp/VIRTEX_R_50_L1_H1024_CC3M/checkpoint_400000.pth --calc-metrics     --num-gpus-per-machine 1     --cpu-workers 4

I am getting eval metrics as zero:
 Iter: 400000 | Metrics: {'CIDEr': 0.0, 'SPICE': 0.0}
