### ISSUE TITLE
Cannot find this file: serialized_train.lmdb

### ISSUE THREAD

**Issue by alibabadoufu** [kdexd/virtex#9]
When I was doing the pretraining, this errors showed up:

`lmdb.Error: datasets/coco/serialized_train.lmdb: No such file or directory`

I couldn't any instruction that generates this file. Anyone has this problem?

**Comment by kdexd** [comment]
Hi @alibabadoufu 

These files are generated as per (2) here:
https://kdexd.github.io/virtex/virtex/usage/setup_dependencies.html#preprocess-data

I noticed that I have a small mismatch in file names between default config and instruction. I'll fix this instruction!

**Comment by kdexd** [comment]
Please check updated instructions (2) at the link above — if you already generated this file, please rename it and/or generate a symlink under `datasets/coco` in the root directory of this codebase as described above.

Feel free to re-open if you still face any issues!
